/* AUTO-GENERATED by scripts/discover-remotes.mjs — do not edit */
export const REMOTE_REGISTRY = [
  {
    "name": "dashboard",
    "route": "/dashboard",
    "label": "Dashboard",
    "port": 5001,
    "entry": "http://localhost:5001/remoteEntry.js",
    "packageDir": "mfe-dashboard"
  },
  {
    "name": "orders",
    "route": "/orders",
    "label": "Orders",
    "port": 5002,
    "entry": "http://localhost:5002/remoteEntry.js",
    "packageDir": "mfe-orders"
  }
] as const;

export type RemoteRegistryEntry = (typeof REMOTE_REGISTRY)[number];
export type RemoteName = RemoteRegistryEntry['name'];
