/* AUTO-GENERATED by scripts/discover-remotes.mjs */
import type { RemoteName } from './registry.generated';

export const remoteLoaders: Record<
  RemoteName,
  () => Promise<{ default: React.ComponentType }>
> = {
  dashboard: () => import('dashboard/App') as Promise<{ default: React.ComponentType }>,
  orders: () => import('orders/App') as Promise<{ default: React.ComponentType }>,
};
