#!/usr/bin/env node
/**
 * Auto-discover remotes from workspace (mfe-* packages + vite federation name + dev port).
 * Writes generated manifest and TypeScript registry for the shell.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  discoverRemotes,
  remotesToManifest,
} from '../config/discover-remotes.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SHELL_ROOT = ROOT;

const remotes = discoverRemotes(resolve(SHELL_ROOT, 'public/manifest.json'));
const manifest = remotesToManifest(remotes);

const manifestPath = resolve(SHELL_ROOT, 'public/manifest.json');
writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf-8');

const registryTs = `/* AUTO-GENERATED by scripts/discover-remotes.mjs — do not edit */
export const REMOTE_REGISTRY = ${JSON.stringify(
  remotes.map((r) => ({
    name: r.name,
    route: r.route,
    label: r.label,
    port: r.port,
    entry: r.entry,
    packageDir: r.packageDir,
  })),
  null,
  2,
)} as const;

export type RemoteRegistryEntry = (typeof REMOTE_REGISTRY)[number];
export type RemoteName = RemoteRegistryEntry['name'];
`;

const registryDir = resolve(SHELL_ROOT, 'src/remotes');
mkdirSync(registryDir, { recursive: true });
writeFileSync(
  resolve(registryDir, 'registry.generated.ts'),
  registryTs,
  'utf-8',
);

const dts = remotes
  .map(
    (r) =>
      `declare module '${r.name}/App' {
  import type { ComponentType } from 'react';
  const App: ComponentType;
  export default App;
}`,
  )
  .join('\n\n');

writeFileSync(
  resolve(ROOT, 'mfe-shell/src/remotes/remotes.generated.d.ts'),
  `/* AUTO-GENERATED */\n${dts}\n`,
  'utf-8',
);

const loadersTs = `/* AUTO-GENERATED by scripts/discover-remotes.mjs */
import type { RemoteName } from './registry.generated';

export const remoteLoaders: Record<
  RemoteName,
  () => Promise<{ default: React.ComponentType }>
> = {
${remotes
  .map(
    (r) =>
      `  ${r.name}: () => import('${r.name}/App') as Promise<{ default: React.ComponentType }>,`,
  )
  .join('\n')}
};
`;

writeFileSync(
  resolve(registryDir, 'remote-loaders.generated.ts'),
  loadersTs,
  'utf-8',
);

console.log(`[discover-remotes] Found ${remotes.length} remote(s):`);
for (const r of remotes) {
  console.log(`  - ${r.name} → ${r.entry} (${r.route})`);
}
console.log(`[discover-remotes] Wrote ${manifestPath}`);
